---
# - name: Copy artifact to server
#   copy:
#     src: files/artifact.tar.gz
#     dest: ~/web/

- name: Unarchive the artifact
  unarchive: 
    src: files/artifact.tar.gz
    dest: ~/web/

- name: Start app
  shell: |
    cd ~/web
    npm install
    pm2 stop default
    pm2 start npm -- start

