---
# - name: Copy artifact to server
#   copy:
#     src: artifact.tar.gz

- name: Unarchive the artifact
  unarchive: 

- name: Start app
  shell: |
    cd artifact
    npm install
    pm2 stop default
    pm2 start npm -- start

