---
# - name: Copy artifact to server
#   copy:
#     src: files/artifact.tar.gz
#     dest: ~/web/

- name: Creates directory
  become: true
  file:
    path: ~/web/
    state: directory

- name: Unarchive the artifact
  become: true
  unarchive: 
    src: files/artifact.tar.gz
    dest: ~/web/

- name: Start app
  become: true
  shell: |
    cd ~/web/
    npm install
    pm2 stop default
    pm2 start npm -- start

